import React from 'react';

function moviesCards (props) {

return([
    {
    "country": "нечто1",
    "director": "некто1",
    "duration": "10",
    "year": "2022",
    "description": "не знаю что1",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "1 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "1"
    },
    {
    "country": "нечто2",
    "director": "некто2",
    "duration": "20",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "2 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "2",
    "owner": "633490f552e1e44d60014077"
    },
    {
    "country": "нечто3",
    "director": "некто3",
    "duration": "30",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "3 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "3"
    },
    {
    "country": "нечто4",
    "director": "некто4",
    "duration": "40",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "4 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "4",
    "owner": "633490f552e1e44d60014077"
    },
    {
    "country": "нечто5",
    "director": "некто5",
    "duration": "50",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "5 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "5"
    },
    {
    "country": "нечт6",
    "director": "некто6",
    "duration": "60",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "6 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "6",
    "owner": "633490f552e1e44d60014077"
    },
    {
    "country": "нечто7",
    "director": "некто7",
    "duration": "70",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "7 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "7"
    },
    {
    "country": "нечто8",
    "director": "некто8",
    "duration": "80",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "8 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "8",
    "owner": "633490f552e1e44d60014077"
    },
    {
    "country": "нечто9",
    "director": "некто9",
    "duration": "90",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "9 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "9"
    },
    {
    "country": "нечто10",
    "director": "некто10",
    "duration": "100",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "10 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "10",
    "owner": "633490f552e1e44d60014077"
    },
    {
    "country": "нечто11",
    "director": "некто11",
    "duration": "110",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "11 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "11"
    },
    {
    "country": "нечто12",
    "director": "некто12",
    "duration": "120",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "12 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "12",
    "owner": "633490f552e1e44d60014077"
    },
    {
    "country": "нечто13",
    "director": "некто13",
    "duration": "130",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "13 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "13",
    "owner": "633490f552e1e44d60014077"
    },
    {
    "country": "нечто14",
    "director": "некто14",
    "duration": "140",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "14 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "14",
    "owner": "633490f552e1e44d60014077"
    },
    {
    "country": "нечто15",
    "director": "некто15",
    "duration": "150",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "15 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "15"
    },
    {
    "country": "нечто16",
    "director": "некто16",
    "duration": "160",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "16 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "16",
    "owner": "633490f552e1e44d60014077"
    },
    {
    "country": "нечто17",
    "director": "некто17",
    "duration": "170",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "17 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "17"
    },
    {
    "country": "нечто18",
    "director": "некто18",
    "duration": "180",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "18 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "18"
    },
    {
    "country": "нечто19",
    "director": "некто19",
    "duration": "190",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "19 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "19"
    },
    {
    "country": "нечто20",
    "director": "некто20",
    "duration": "200",
    "year": "2022",
    "description": "не знаю что",
    "image": "https://practicum.yandex.ru/",
    "trailerLink": "https://practicum.yandex.ru/",
    "nameRU": "20 слова о дизайне",
    "nameEN": "название на английском",
    "thumbnail": "https://practicum.yandex.ru/",
    "movieId": "20",
    "owner": "633490f552e1e44d60014077"
  }])
}

export default moviesCards